-- SQL script that creates a view need_meeting that lists all students that have a score under 80 (strict) and no last_meeting or more than 1 month.
-- Requirements:
-- The view need_meeting should return all students name when:
-- They score are under (strict) to 80
